
> zenith@0.1.0 dev:tunnel
> node start-with-tunnel.js

Starting Next.js development server on port 3002...
Next.js server started. Setting up localtunnel...
 тип Failed to start server
Error: listen EADDRINUSE: address already in use :::3002
    at Server.setupListenHandle [as _listen2] (node:net:1940:16)
    at listenInCluster (node:net:1997:12)
    at Server.listen (node:net:2102:7)
    at /Users/test/Startups/zenith/node_modules/next/dist/server/lib/start-server.js:280:16
    at new Promise (<anonymous>)
    at startServer (/Users/test/Startups/zenith/node_modules/next/dist/server/lib/start-server.js:191:11)
    at /Users/test/Startups/zenith/node_modules/next/dist/server/lib/start-server.js:310:52
    at Span.traceAsyncFn (/Users/test/Startups/zenith/node_modules/next/dist/trace/trace.js:154:26)
    at process.<anonymous> (/Users/test/Startups/zenith/node_modules/next/dist/server/lib/start-server.js:310:35)
    at process.emit (node:events:518:28) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3002
}
[?25h
Next.js server exited with code 0
LocalTunnel URL: https://zenith-signimus.loca.lt
Facebook OAuth should now work with this URL
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: localtunnel.me:18567 (check your firewall settings)
    at Socket.<anonymous> (/Users/te[?25h
tups/zenith/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
    at Socket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Emitted 'error' event on Tunnel instance at:
    at TunnelCluster.<anonymous> (/Users/test/Startups/zenith/node_modules/localtunnel/lib/Tunnel.js:96:12)
    at TunnelCluster.emit (node:events:518:28)
    at Socket.<anonymous> (/Users/test/Startups/zenith/node_modules/localtunnel/lib/TunnelCluster.js:50:14)
    at Socket.emit (node:events:518:28)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

Node.js v22.18.0
